name: donate

on:
  issues:
    types: [opened, closed]
  schedule:
    # Change 0 to random value in [0,60]
    - cron: '0 * * * *' # for updating balance

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - env:
          #
          # See https://github.com/jollheef/donate/blob/master/dashboard/whitelist.go
          #
          # You can safely comment it out if you don't want to have
          # your issues with donations on a global dashboard (across
          # all instances of _donate_) at https://donate.dumpstack.io
          #
          # However, I strongly suggest you add yourself to whitelist,
          # then people will able to find your project's issues.
          #
          DASHBOARD_ACCESS_TOKEN: ${{ secrets.DONATE_DASHBOARD_ACCESS_TOKEN }}
          #
          # For self-hosted installations.
          #
          #DONATE_ENDPOINT: ...
          #
          # The scope of default GitHub token is the current repository only.
          # Token required to posting comments on the issues.
          #
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #
          TOOL: "https://github.com/jollheef/donate/archive/master.tar.gz"
        run: |
          curl -L https://nixos.org/nix/install | sh
          . ~/.nix-profile/etc/profile.d/nix.sh
          # Use latest stable nixpkgs channel
          nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
          nix-channel --update
          nix run -f $TOOL -c donate-ci
